### ISSUE TITLE
Set up mc aliases for dr1 and dr2

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#1163]
Each time we start a cluster we get different ip adddress, so we can use static aliases.

To create mc alias we need to use:

```console
$ mc alias set dr1 $(minikube service minio -n minio --url -p dr1) minio minio123
Added `dr1` successfully.

$ mc alias set dr2 $(minikube service minio -n minio --url -p dr2) minio minio123
Added `dr2` successfully.
```

The best place to set the alias is in minio/start hook - we need it anyway for a self
test #743.

We need also aliases for external clusters (e.g. ocp), this can done separately.

## Tasks

- [ ] Add mc to tools (#1280)
- [ ] Add mc alias in minio/start
- [ ] Remove mc alias in minio/delete?
