### ISSUE TITLE
velero backup/restore fails with zero exit code

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#1281]
We have rare error in velero test, when restoring the backup fails. Looking earlier in the log, we see that the backup failed - but the `velero backup` command exited with zero exit code.

## Creating a backup

```
2024-03-22 22:31:10,277 DEBUG   [dr2/2] Backing up nginx example
2024-03-22 22:31:10,277 DEBUG   [dr2/2] Creating backup nginx-backup with selector app=nginx
2024-03-22 22:31:10,388 DEBUG   [dr2/2] Backup request "nginx-backup" submitted successfully.
2024-03-22 22:31:10,388 DEBUG   [dr2/2] Waiting for backup to complete. You may safely press ctrl-c to stop waiting - your backup will continue in the background.
2024-03-22 22:31:15,438 DEBUG   [dr2/2] .....
2024-03-22 22:31:15,438 DEBUG   [dr2/2] Backup completed with status: Failed. You may check for more information using the commands `velero backup describe nginx-backup` and `velero backup logs nginx-backup`.
```

The backup command reports a failure, but the command exit with zero exit code.

After the backup we print a description of the backup for debugging, but we don't check the contents:

```
2024-03-22 22:31:45,447 DEBUG   [dr2/2] Name:         ^[[1mnginx-backup^[[0m
2024-03-22 22:31:45,447 DEBUG   [dr2/2] Namespace:    velero
2024-03-22 22:31:45,447 DEBUG   [dr2/2] Labels:       velero.io/storage-location=default
2024-03-22 22:31:45,447 DEBUG   [dr2/2] Annotations:  velero.io/resource-timeout=10m0s
2024-03-22 22:31:45,447 DEBUG   [dr2/2]               velero.io/source-cluster-k8s-gitversion=v1.28.3
2024-03-22 22:31:45,447 DEBUG   [dr2/2]               velero.io/source-cluster-k8s-major-version=1
2024-03-22 22:31:45,447 DEBUG   [dr2/2]               velero.io/source-cluster-k8s-minor-version=28
2024-03-22 22:31:45,447 DEBUG   [dr2/2]
2024-03-22 22:31:45,447 DEBUG   [dr2/2] Phase:  ^[[31mFailed^[[0m (run `velero backup logs nginx-backup` for more information)
```

Than we try to restore and the restore fails (because the backup failed?):

```
2024-03-22 22:31:56,487 DEBUG   [dr2/2] Restoring nginx-backup from backup
2024-03-22 22:31:56,607 DEBUG   [dr2/2] Restore request "nginx-backup-20240322223156" submitted successfully.
2024-03-22 22:31:56,607 DEBUG   [dr2/2] Waiting for restore to complete. You may safely press ctrl-c to stop waiting - your restore will continue in the background.
2024-03-22 22:31:56,799 DEBUG   [dr2/2]
2024-03-22 22:31:56,799 DEBUG   [dr2/2] Restore completed with status: Failed. You may check for more information using the commands `velero restore describe nginx-backup-20240322223156` and `velero restore logs nginx-backup-20240322223156`.
2024-03-22 22:31:56,923 DEBUG   [dr2/2] Name:         ^[[1mnginx-backup-20240322223156^[[0m
2024-03-22 22:31:56,923 DEBUG   [dr2/2] Namespace:    velero
2024-03-22 22:31:56,923 DEBUG   [dr2/2] Labels:       <none>
2024-03-22 22:31:56,923 DEBUG   [dr2/2] Annotations:  <none>
2024-03-22 22:31:56,923 DEBUG   [dr2/2]
2024-03-22 22:31:56,923 DEBUG   [dr2/2] Phase:  ^[[31mFailed^[[0m (run 'velero restore logs nginx-backup-20240322223156' for more information)
```

Again the command return with zero exit code, and describing the backup show the failure. We don't check the restore description and continue to validate the restore:

```
2024-03-22 22:31:56,924 DEBUG   [dr2/2] Verifying nginx example deployment
2024-03-22 22:31:57,024 ERROR   Command failed
Traceback (most recent call last):
...
drenv.commands.Error: Command failed:
   command: ('addons/velero/test', 'dr2')
   exitcode: 1
   error:
      Traceback (most recent call last):
        File "/home/nsoffer/ramen/test/addons/velero/test", line 164, in <module>
          test(cluster)
        File "/home/nsoffer/ramen/test/addons/velero/test", line 46, in test
          kubectl.rollout(
        File "/home/nsoffer/ramen/test/drenv/kubectl.py", line 122, in rollout
          _watch("rollout", *args, context=context, log=log)
        File "/home/nsoffer/ramen/test/drenv/kubectl.py", line 145, in _watch
          for line in commands.watch(*cmd, input=input):
        File "/home/nsoffer/ramen/test/drenv/commands.py", line 154, in watch
          raise Error(args, error, exitcode=p.returncode)
      drenv.commands.Error: Command failed:
         command: ('kubectl', 'rollout', '--context', 'dr2', 'status', 'deploy/nginx-deployment', '--namespace=nginx-example', '--timeout=120s')
         exitcode: 1
         error:
            Error from server (NotFound): namespaces "nginx-example" not found
```

## System state after the error

```
$ velero backup get --kubecontext dr2
NAME           STATUS   ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
nginx-backup   Failed   0        0          2024-03-22 22:31:10 +0200 IST   29d       default            app=nginx
```

```
$ velero backup get nginx-backup --kubecontext dr2 -o yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/resource-timeout: 10m0s
    velero.io/source-cluster-k8s-gitversion: v1.28.3
    velero.io/source-cluster-k8s-major-version: "1"
    velero.io/source-cluster-k8s-minor-version: "28"
  creationTimestamp: "2024-03-22T20:31:10Z"
  generation: 5
  labels:
    velero.io/storage-location: default
  managedFields:
  - apiVersion: velero.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:hooks: {}
        f:includedNamespaces: {}
        f:labelSelector: {}
        f:metadata: {}
      f:status: {}
    manager: velero
    operation: Update
    time: "2024-03-22T20:31:10Z"
  - apiVersion: velero.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:velero.io/resource-timeout: {}
          f:velero.io/source-cluster-k8s-gitversion: {}
          f:velero.io/source-cluster-k8s-major-version: {}
          f:velero.io/source-cluster-k8s-minor-version: {}
        f:labels:
          .: {}
          f:velero.io/storage-location: {}
      f:spec:
        f:csiSnapshotTimeout: {}
        f:defaultVolumesToFsBackup: {}
        f:itemOperationTimeout: {}
        f:snapshotMoveData: {}
        f:storageLocation: {}
        f:ttl: {}
      f:status:
        f:expiration: {}
        f:failureReason: {}
        f:formatVersion: {}
        f:phase: {}
        f:progress:
          .: {}
          f:itemsBackedUp: {}
          f:totalItems: {}
        f:startTimestamp: {}
        f:version: {}
    manager: velero-server
    operation: Update
    time: "2024-03-22T20:31:15Z"
  name: nginx-backup
  namespace: velero
  resourceVersion: "3027"
  uid: 7494a189-35bc-4898-b926-055b93593e3f
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: false
  hooks: {}
  includedNamespaces:
  - '*'
  itemOperationTimeout: 4h0m0s
  labelSelector:
    matchLabels:
      app: nginx
  metadata: {}
  snapshotMoveData: false
  storageLocation: default
  ttl: 720h0m0s
status:
  expiration: "2024-04-21T20:31:10Z"
  failureReason: "rpc error: code = Unknown desc = error putting object backups/nginx-backup/velero-backup.json:
    NoSuchBucket: The specified bucket does not exist\n\tstatus code: 404, request
    id: 17BF304971BC977B, host id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8"
  formatVersion: 1.1.0
  phase: Failed
  progress:
    itemsBackedUp: 23
    totalItems: 23
  startTimestamp: "2024-03-22T20:31:10Z"
  version: 1
```

## Velero log

```
time="2024-03-22T20:30:59Z" level=error msg="Error listing backups in backup store" backupLocation=velero/default controller=backup-sync error="rpc error: code = Unknown desc = NoSuchBucket: The specified bucket does not exist\n\tstatus code: 404, request id: 17BF3045A2F94175, host id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:361" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:107"
time="2024-03-22T20:30:59Z" level=error msg="fail to validate backup store" backup-storage-location=velero/default controller=backup-storage-location error="rpc error: code = Unknown desc = NoSuchBucket: The specified bucket does not exist\n\tstatus code: 404, request id: 17BF3045A3206114, host id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/persistence/object_store.go:198" error.function="github.com/vmware-tanzu/velero/pkg/persistence.(*objectBackupStore).IsValid" logSource="pkg/controller/backup_storage_location_controller.go:155"
time="2024-03-22T20:30:59Z" level=info msg="BackupStorageLocation is invalid, marking as unavailable" backup-storage-location=velero/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:131"
time="2024-03-22T20:30:59Z" level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/0/1, BackupStorageLocation \"default\" is unavailable: rpc error: code = Unknown desc = NoSuchBucket: The specified bucket does not exist\n\tstatus code: 404, request id: 17BF3045A3206114, host id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:192"

```

[velero.log](https://github.com/RamenDR/ramen/files/14728574/velero.log)

## minio status

minio looks correct but maybe it was not functional when velero tried to use it.

```
$ kubectl get all -n minio --context dr2
NAME                         READY   STATUS      RESTARTS   AGE
pod/minio-6589cfb67b-2h8rp   1/1     Running     0          53m
pod/minio-setup-cqrrf        0/1     Completed   4          53m

NAME            TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
service/minio   NodePort   10.107.169.116   <none>        9000:30000/TCP   53m

NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/minio   1/1     1            1           53m

NAME                               DESIRED   CURRENT   READY   AGE
replicaset.apps/minio-6589cfb67b   1         1         1       53m

NAME                    COMPLETIONS   DURATION   AGE
job.batch/minio-setup   1/1           2m8s       53m

$ mc ls dr2/
[2024-03-22 22:31:20 IST]     0B bucket/
```

```
$ kubectl logs deploy/minio -n minio --context dr2
WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
         Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
Formatting 1st pool, 1 set(s), 1 drives per set.
WARNING: Host local has more than 0 drives of set. A host failure will result in data becoming unavailable.
MinIO Object Storage Server
Copyright: 2015-2024 MinIO, Inc.
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Version: RELEASE.2024-03-21T23-13-43Z (go1.21.8 linux/amd64)

API: http://10.244.0.31:9000  http://127.0.0.1:9000 
WebUI: http://10.244.0.31:35251 http://127.0.0.1:35251   

Docs: https://min.io/docs/minio/linux/index.html
Status:         1 Online, 0 Offline. 
STARTUP WARNINGS:
- The standard parity is set to 0. This can lead to data loss.

API: ListObjectsV2(bucket=bucket)
Time: 20:30:59 UTC 03/22/2024
DeploymentID: e5c2f893-7598-4de0-a5fb-17d590e7aa22
RequestID: 17BF3045A2F94175
RemoteHost: 10.244.0.1
Host: 192.168.22.144:30000
UserAgent: aws-sdk-go/1.30.13 (go1.13.15; linux; amd64)
Error: volume not found (cmd.StorageErr)
       7: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
       6: internal/logger/logonce.go:149:logger.LogOnceIf()
       5: cmd/erasure-server-pool.go:1521:cmd.(*erasureServerPools).listObjectsGeneric()
       4: cmd/erasure-server-pool.go:1279:cmd.(*erasureServerPools).ListObjectsV2()
       3: cmd/bucket-listobjects-handlers.go:210:cmd.objectAPIHandlers.listObjectsV2Handler()
       2: cmd/bucket-listobjects-handlers.go:156:cmd.objectAPIHandlers.ListObjectsV2Handler()
       1: net/http/server.go:2136:http.HandlerFunc.ServeHTTP()
```

Testing minio functionality:

```
$ echo 'testing 1 2 3' > data

$ mc cp data dr2/bucket/test

$ mc ls dr2/bucket
[2024-03-22 23:29:06 IST]    14B STANDARD test

$ mc cat dr2/bucket/test | sha256sum
db6d415937a49aaadc7ed0c9acb864cfd314792a31856a3e980a988631e434e2  -

$ sha256sum data
db6d415937a49aaadc7ed0c9acb864cfd314792a31856a3e980a988631e434e2  data
```

So minio is ok, at least at the time of the check, but maybe it has an
error when velero tried to use it?

The bucket is created by the minio-setup job:

```
$ kubectl get job minio-setup -n minio --context dr2 -o yaml
...
status:
  completionTime: "2024-03-22T20:31:22Z"
...
```

The failed backup was on:

```
2024-03-22 22:31:10,277 DEBUG   [dr2/2] Creating backup nginx-backup with selector app=nginx
...
2024-03-22 22:31:15,438 DEBUG   [dr2/2] Backup completed with status: Failed. You may check for more information using the commands `velero backup describe nginx-backup` and `velero backup logs nginx-backup`.
```

```
$ timedatectl
               Local time: Fri 2024-03-22 23:43:39 IST
                Time zone: Asia/Jerusalem (IST, +0200)
```

So looks like the issue is that the minio-setup job completed 5 seconds
*after* the backup, since we don't wait for the minio-setup job. The job can
be slow since it need to pull the mc image. If the network is slow this can
take lot of time.

## Tasks

- [ ] Wait for minio-setup job in `test/addon/minio/start`
- [ ] Check the backup/restore after the operation completes and fail early
- [ ] Open velero bug to report non-zero exit code on errors
