### ISSUE TITLE
minio consumes all available memory, other addons fails with "net/http: TLS handshake timeout"

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#1282]
We have random unexplained timeouts when waiting for ceph cluster or pool.

```
drenv.commands.Error: Command failed:
   command: ('addons/rook-cluster/start', 'dr1')
   exitcode: 1
   error:
      Traceback (most recent call last):
        File "/home/nsoffer/src/ramen/test/addons/rook-cluster/start", line 51, in <module>
          wait(cluster)
        File "/home/nsoffer/src/ramen/test/addons/rook-cluster/start", line 34, in wait
          kubectl.wait(
        File "/home/nsoffer/src/ramen/test/drenv/kubectl.py", line 129, in wait
          _watch("wait", *args, context=context, log=log)
        File "/home/nsoffer/src/ramen/test/drenv/kubectl.py", line 145, in _watch
          for line in commands.watch(*cmd, input=input):
        File "/home/nsoffer/src/ramen/test/drenv/commands.py", line 154, in watch
          raise Error(args, error, exitcode=p.returncode)
      drenv.commands.Error: Command failed:
         command: ('kubectl', 'wait', '--context', 'dr1', 'cephcluster/my-cluster', '--for=jsonpath={.status.phase}=Ready', '--namespace
=rook-ceph', '--timeout=300s')
         exitcode: 1
         error:
            W0323 23:33:54.217650 4119190 reflector.go:458] vendor/k8s.io/client-go/tools/watch/informerwatcher.go:146: watch of *unstru
ctured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost"
) has prevented the request from succeeding
            W0323 23:34:05.804964 4119190 reflector.go:535] vendor/k8s.io/client-go/tools/watch/informerwatcher.go:146: failed to list *
unstructured.Unstructured: Get "https://192.168.122.168:8443/apis/ceph.rook.io/v1/namespaces/rook-ceph/cephclusters?fieldSelector=metada
ta.name%3Dmy-cluster&resourceVersion=3272": net/http: TLS handshake timeout
            ...
            E0323 23:35:21.523071 4119190 reflector.go:147] vendor/k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Get "https://192.168.122.168:8443/apis/ceph.rook.io/v1/namespaces/rook-ceph/cephclusters?fieldSelector=metadata.name%3Dmy-cluster&resourceVersion=3272": net/http: TLS handshake timeout
            error: timed out waiting for the condition on cephclusters/my-cluster
```

Looking at a cluster in one of the failures, we see that minio consumes 2.1g of memory, the host
is at 400% cpu and swapping (kswapd uses 60+% cpu).

Trying to access the cluster with kubectl fails with "net/http: TLS handshake timeout"

Normally minio uses 150m of memory - this look like a bug in minio. We use latest so it can break randomly.

Seen with this image:
https://quay.io/repository/minio/minio/manifest/sha256:15f67762662faecbca7b4b90220f93cf451ba3d8af6a48664903077e4603c8cd

## Tasks

- [ ] Use latest release instead of latest?
  - https://github.com/minio/minio/releases/tag/RELEASE.2024-03-21T23-13-43Z
- [ ] Configure minio memory limit for container?
  - Will it kill the process if it reaches the limit?
- [ ] Try to reproduce and open minio issue
- [ ] Collect data from cluster on failures (#1283)
