### ISSUE TITLE
Cache addons resources

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#1290]
In the e2e lab we have flaky network making downloads from github slow and unreliable. In some cases like ocm-controller, applying kustmization can fail when the remote server disconnects. We want to cache all resources consumed from github to make builds faster and more reliable.

Caching resources is not enough, we need to cache also container images. This will be tracked in a separate issue.

## Addons that can be cached

These addons use a static kustomization that can be cached by the current caching infrastructure.

- [x] cdi (fixed by #1317)
  - operator needs caching
  - cr needs caching
- [x] kubevirt (fixed by #1317)
  - operator needs caching
  - cr needs caching
- [x] ocm-controller (fixed by #1239) 

See ocm-controller hooks for example:
- [start hook](https://github.com/RamenDR/ramen/blob/930463d87fcbf91eda11dc43175351a570298dc2/test/addons/ocm-controller/start#L15)
- [fetch hook](https://github.com/RamenDR/ramen/blob/main/test/addons/ocm-controller/fetch)

## Addons accessing resources directly

These addons apply resources directly from github.

We have 2 options:
- Change the cache to support standalone resources
- Convert them to static kustomization

Using static kustomization sounds a better way since it is easier to test with standard tools, and support easy way to modify the resources (e.g. replace image tags or prefix names).

- [ ] olm (issue #1337)
- [x] recipe (issue #1330, fixed by #1351)

## Addons using kustomization templates

Use a kustomization template used to create a temporary kustomization file with replaced values.
We have 2 options:
- Cache the temporary kustomization
- Convert to static kustomization

Getting rid of the kustomization templates sounds the better way. Static kustomization are easier to understand and test using standard tools.

- [x] csi-addons (fixed by #1351)
- [x] rook-operator (fixed by #1353)
- [x] rook-cluster (issue #1310, fixed by #1353)
- [x] rook-toolbox (fixed by #1353)

## Addons using external tools

These addons use external tool for deployment. The tool may access remote resources but we are not in control.

We can check if the tool support caching in some way.

- ocm-cluster - uses clusteradm
- ocm-hub - uses clusteradm
- velero - uses velero
- volsync - uses helm
- submariner - uses subctl

## Addons using local or no resources
 
- demo
- example
- minio
- rook-pool
- rbd-mirror
- sleep
- error

**Comment by nirs** [comment]
@abhijeet219 is working on this.
