### ISSUE TITLE
Timeout waiting for rbd mirror daemon health

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#1322]
Sometimes after configuring rbd mirroring the rbd-daemon never becomes ready.

Example log:
```
$ grep -E '(dr1/0|rdr/0)' out/029.log 
2024-04-04 23:58:40,122 INFO    [dr1/0] Running addons/rook-operator/start
2024-04-04 23:58:40,305 DEBUG   [dr1/0] Deploying rook ceph operator
2024-04-04 23:58:43,523 DEBUG   [dr1/0] namespace/rook-ceph created
2024-04-04 23:58:43,551 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/cephblockpoolradosnamespaces.ceph.rook.io created
2024-04-04 23:58:43,594 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/cephblockpools.ceph.rook.io created
2024-04-04 23:58:43,637 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/cephbucketnotifications.ceph.rook.io created
2024-04-04 23:58:43,664 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/cephbuckettopics.ceph.rook.io created
2024-04-04 23:58:43,705 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/cephclients.ceph.rook.io created
2024-04-04 23:58:43,982 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/cephclusters.ceph.rook.io created
2024-04-04 23:58:44,024 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/cephcosidrivers.ceph.rook.io created
2024-04-04 23:58:44,065 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/cephfilesystemmirrors.ceph.rook.io created
2024-04-04 23:58:44,249 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/cephfilesystems.ceph.rook.io created
2024-04-04 23:58:44,329 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/cephfilesystemsubvolumegroups.ceph.rook.io created
2024-04-04 23:58:44,434 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/cephnfses.ceph.rook.io created
2024-04-04 23:58:44,469 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/cephobjectrealms.ceph.rook.io created
2024-04-04 23:58:44,648 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/cephobjectstores.ceph.rook.io created
2024-04-04 23:58:44,694 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/cephobjectstoreusers.ceph.rook.io created
2024-04-04 23:58:44,872 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/cephobjectzonegroups.ceph.rook.io created
2024-04-04 23:58:44,937 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/cephobjectzones.ceph.rook.io created
2024-04-04 23:58:45,000 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/cephrbdmirrors.ceph.rook.io created
2024-04-04 23:58:45,030 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/objectbucketclaims.objectbucket.io created
2024-04-04 23:58:45,083 DEBUG   [dr1/0] customresourcedefinition.apiextensions.k8s.io/objectbuckets.objectbucket.io created
2024-04-04 23:58:45,122 DEBUG   [dr1/0] serviceaccount/objectstorage-provisioner created
2024-04-04 23:58:45,154 DEBUG   [dr1/0] serviceaccount/rook-ceph-cmd-reporter created
2024-04-04 23:58:45,213 DEBUG   [dr1/0] serviceaccount/rook-ceph-mgr created
2024-04-04 23:58:45,231 DEBUG   [dr1/0] serviceaccount/rook-ceph-osd created
2024-04-04 23:58:45,250 DEBUG   [dr1/0] serviceaccount/rook-ceph-purge-osd created
2024-04-04 23:58:45,264 DEBUG   [dr1/0] serviceaccount/rook-ceph-rgw created
2024-04-04 23:58:45,279 DEBUG   [dr1/0] serviceaccount/rook-ceph-system created
2024-04-04 23:58:45,294 DEBUG   [dr1/0] serviceaccount/rook-csi-cephfs-plugin-sa created
2024-04-04 23:58:45,316 DEBUG   [dr1/0] serviceaccount/rook-csi-cephfs-provisioner-sa created
2024-04-04 23:58:45,338 DEBUG   [dr1/0] serviceaccount/rook-csi-rbd-plugin-sa created
2024-04-04 23:58:45,352 DEBUG   [dr1/0] serviceaccount/rook-csi-rbd-provisioner-sa created
2024-04-04 23:58:45,366 DEBUG   [dr1/0] role.rbac.authorization.k8s.io/cephfs-external-provisioner-cfg created
2024-04-04 23:58:45,380 DEBUG   [dr1/0] role.rbac.authorization.k8s.io/rbd-csi-nodeplugin created
2024-04-04 23:58:45,403 DEBUG   [dr1/0] role.rbac.authorization.k8s.io/rbd-external-provisioner-cfg created
2024-04-04 23:58:45,421 DEBUG   [dr1/0] role.rbac.authorization.k8s.io/rook-ceph-cmd-reporter created
2024-04-04 23:58:45,437 DEBUG   [dr1/0] role.rbac.authorization.k8s.io/rook-ceph-mgr created
2024-04-04 23:58:45,459 DEBUG   [dr1/0] role.rbac.authorization.k8s.io/rook-ceph-osd created
2024-04-04 23:58:45,478 DEBUG   [dr1/0] role.rbac.authorization.k8s.io/rook-ceph-purge-osd created
2024-04-04 23:58:45,496 DEBUG   [dr1/0] role.rbac.authorization.k8s.io/rook-ceph-rgw created
2024-04-04 23:58:45,521 DEBUG   [dr1/0] role.rbac.authorization.k8s.io/rook-ceph-system created
2024-04-04 23:58:45,531 DEBUG   [dr1/0] clusterrole.rbac.authorization.k8s.io/cephfs-csi-nodeplugin created
2024-04-04 23:58:45,548 DEBUG   [dr1/0] clusterrole.rbac.authorization.k8s.io/cephfs-external-provisioner-runner created
2024-04-04 23:58:45,558 DEBUG   [dr1/0] clusterrole.rbac.authorization.k8s.io/objectstorage-provisioner-role created
2024-04-04 23:58:45,570 DEBUG   [dr1/0] clusterrole.rbac.authorization.k8s.io/rbd-csi-nodeplugin created
2024-04-04 23:58:45,584 DEBUG   [dr1/0] clusterrole.rbac.authorization.k8s.io/rbd-external-provisioner-runner created
2024-04-04 23:58:45,597 DEBUG   [dr1/0] clusterrole.rbac.authorization.k8s.io/rook-ceph-cluster-mgmt created
2024-04-04 23:58:45,609 DEBUG   [dr1/0] clusterrole.rbac.authorization.k8s.io/rook-ceph-global created
2024-04-04 23:58:45,629 DEBUG   [dr1/0] clusterrole.rbac.authorization.k8s.io/rook-ceph-mgr-cluster created
2024-04-04 23:58:45,643 DEBUG   [dr1/0] clusterrole.rbac.authorization.k8s.io/rook-ceph-mgr-system created
2024-04-04 23:58:45,658 DEBUG   [dr1/0] clusterrole.rbac.authorization.k8s.io/rook-ceph-object-bucket created
2024-04-04 23:58:45,667 DEBUG   [dr1/0] clusterrole.rbac.authorization.k8s.io/rook-ceph-osd created
2024-04-04 23:58:45,684 DEBUG   [dr1/0] clusterrole.rbac.authorization.k8s.io/rook-ceph-system created
2024-04-04 23:58:45,698 DEBUG   [dr1/0] rolebinding.rbac.authorization.k8s.io/cephfs-csi-provisioner-role-cfg created
2024-04-04 23:58:45,730 DEBUG   [dr1/0] rolebinding.rbac.authorization.k8s.io/rbd-csi-nodeplugin-role-cfg created
2024-04-04 23:58:45,750 DEBUG   [dr1/0] rolebinding.rbac.authorization.k8s.io/rbd-csi-provisioner-role-cfg created
2024-04-04 23:58:45,783 DEBUG   [dr1/0] rolebinding.rbac.authorization.k8s.io/rook-ceph-cluster-mgmt created
2024-04-04 23:58:45,805 DEBUG   [dr1/0] rolebinding.rbac.authorization.k8s.io/rook-ceph-cmd-reporter created
2024-04-04 23:58:45,822 DEBUG   [dr1/0] rolebinding.rbac.authorization.k8s.io/rook-ceph-mgr created
2024-04-04 23:58:45,840 DEBUG   [dr1/0] rolebinding.rbac.authorization.k8s.io/rook-ceph-mgr-system created
2024-04-04 23:58:45,862 DEBUG   [dr1/0] rolebinding.rbac.authorization.k8s.io/rook-ceph-osd created
2024-04-04 23:58:45,880 DEBUG   [dr1/0] rolebinding.rbac.authorization.k8s.io/rook-ceph-purge-osd created
2024-04-04 23:58:45,899 DEBUG   [dr1/0] rolebinding.rbac.authorization.k8s.io/rook-ceph-rgw created
2024-04-04 23:58:45,918 DEBUG   [dr1/0] rolebinding.rbac.authorization.k8s.io/rook-ceph-system created
2024-04-04 23:58:45,929 DEBUG   [dr1/0] clusterrolebinding.rbac.authorization.k8s.io/cephfs-csi-nodeplugin-role created
2024-04-04 23:58:45,955 DEBUG   [dr1/0] clusterrolebinding.rbac.authorization.k8s.io/cephfs-csi-provisioner-role created
2024-04-04 23:58:45,979 DEBUG   [dr1/0] clusterrolebinding.rbac.authorization.k8s.io/objectstorage-provisioner-role-binding created
2024-04-04 23:58:46,003 DEBUG   [dr1/0] clusterrolebinding.rbac.authorization.k8s.io/rbd-csi-nodeplugin created
2024-04-04 23:58:46,022 DEBUG   [dr1/0] clusterrolebinding.rbac.authorization.k8s.io/rbd-csi-provisioner-role created
2024-04-04 23:58:46,050 DEBUG   [dr1/0] clusterrolebinding.rbac.authorization.k8s.io/rook-ceph-global created
2024-04-04 23:58:46,061 DEBUG   [dr1/0] clusterrolebinding.rbac.authorization.k8s.io/rook-ceph-mgr-cluster created
2024-04-04 23:58:46,084 DEBUG   [dr1/0] clusterrolebinding.rbac.authorization.k8s.io/rook-ceph-object-bucket created
2024-04-04 23:58:46,102 DEBUG   [dr1/0] clusterrolebinding.rbac.authorization.k8s.io/rook-ceph-osd created
2024-04-04 23:58:46,120 DEBUG   [dr1/0] clusterrolebinding.rbac.authorization.k8s.io/rook-ceph-system created
2024-04-04 23:58:46,179 DEBUG   [dr1/0] configmap/rook-ceph-operator-config created
2024-04-04 23:58:46,278 DEBUG   [dr1/0] deployment.apps/rook-ceph-operator created
2024-04-04 23:58:46,287 DEBUG   [dr1/0] Waiting until rook ceph operator is rolled out
2024-04-04 23:58:46,466 DEBUG   [dr1/0] Waiting for deployment "rook-ceph-operator" rollout to finish: 0 of 1 updated replicas are available...
2024-04-04 23:59:30,404 DEBUG   [dr1/0] deployment "rook-ceph-operator" successfully rolled out
2024-04-04 23:59:30,411 DEBUG   [dr1/0] Waiting until rook ceph operator is ready
2024-04-04 23:59:30,640 DEBUG   [dr1/0] pod/rook-ceph-operator-6d6b84b579-fsq29 condition met
2024-04-04 23:59:30,696 INFO    [dr1/0] addons/rook-operator/start completed in 50.57 seconds
2024-04-04 23:59:30,696 INFO    [dr1/0] Running addons/rook-cluster/start
2024-04-04 23:59:30,906 DEBUG   [dr1/0] Deploying rook ceph cluster
2024-04-04 23:59:31,505 DEBUG   [dr1/0] cephblockpool.ceph.rook.io/builtin-mgr created
2024-04-04 23:59:31,528 DEBUG   [dr1/0] cephcluster.ceph.rook.io/my-cluster created
2024-04-04 23:59:31,534 DEBUG   [dr1/0] Waiting for ceph cluster Progressing condition
2024-04-04 23:59:31,763 DEBUG   [dr1/0] cephcluster.ceph.rook.io/my-cluster condition met
2024-04-04 23:59:31,766 DEBUG   [dr1/0] Waiting for ceph cluster Ready condition
2024-04-05 00:02:42,806 DEBUG   [dr1/0] cephcluster.ceph.rook.io/my-cluster condition met
2024-04-05 00:02:43,004 DEBUG   [dr1/0] ceph cluster status:
2024-04-05 00:02:43,004 DEBUG   [dr1/0]   conditions:
2024-04-05 00:02:43,004 DEBUG   [dr1/0]   - lastHeartbeatTime: '2024-04-04T21:02:42Z'
2024-04-05 00:02:43,004 DEBUG   [dr1/0]     lastTransitionTime: '2024-04-04T21:02:42Z'
2024-04-05 00:02:43,004 DEBUG   [dr1/0]     message: Cluster created successfully
2024-04-05 00:02:43,004 DEBUG   [dr1/0]     reason: ClusterCreated
2024-04-05 00:02:43,004 DEBUG   [dr1/0]     status: 'True'
2024-04-05 00:02:43,004 DEBUG   [dr1/0]     type: Ready
2024-04-05 00:02:43,004 DEBUG   [dr1/0]   message: Cluster created successfully
2024-04-05 00:02:43,004 DEBUG   [dr1/0]   observedGeneration: 2
2024-04-05 00:02:43,004 DEBUG   [dr1/0]   phase: Ready
2024-04-05 00:02:43,005 DEBUG   [dr1/0]   state: Created
2024-04-05 00:02:43,005 DEBUG   [dr1/0]   storage:
2024-04-05 00:02:43,005 DEBUG   [dr1/0]     osd:
2024-04-05 00:02:43,005 DEBUG   [dr1/0]       storeType:
2024-04-05 00:02:43,005 DEBUG   [dr1/0]         bluestore: 1
2024-04-05 00:02:43,005 DEBUG   [dr1/0]   version:
2024-04-05 00:02:43,005 DEBUG   [dr1/0]     image: quay.io/ceph/ceph:v18
2024-04-05 00:02:43,005 DEBUG   [dr1/0]     version: 18.2.2-0
2024-04-05 00:02:43,005 DEBUG   [dr1/0] 
2024-04-05 00:02:43,044 INFO    [dr1/0] addons/rook-cluster/start completed in 192.35 seconds
2024-04-05 00:02:43,044 INFO    [dr1/0] Running addons/rook-toolbox/start
2024-04-05 00:02:43,245 DEBUG   [dr1/0] Deploying rook ceph toolbox
2024-04-05 00:02:43,921 DEBUG   [dr1/0] deployment.apps/rook-ceph-tools created
2024-04-05 00:02:43,926 DEBUG   [dr1/0] Waiting until rook-ceph-tools is rolled out
2024-04-05 00:02:44,201 DEBUG   [dr1/0] Waiting for deployment "rook-ceph-tools" rollout to finish: 0 out of 1 new replicas have been updated...
2024-04-05 00:02:44,247 DEBUG   [dr1/0] Waiting for deployment "rook-ceph-tools" rollout to finish: 0 of 1 updated replicas are available...
2024-04-05 00:02:50,607 DEBUG   [dr1/0] deployment "rook-ceph-tools" successfully rolled out
2024-04-05 00:02:50,611 DEBUG   [dr1/0] ceph status:
2024-04-05 00:02:54,391 DEBUG   [dr1/0]   cluster:
2024-04-05 00:02:54,391 DEBUG   [dr1/0]     id:     34169d10-23bb-4087-b218-6b474627b8e7
2024-04-05 00:02:54,391 DEBUG   [dr1/0]     health: HEALTH_OK
2024-04-05 00:02:54,391 DEBUG   [dr1/0] 
2024-04-05 00:02:54,391 DEBUG   [dr1/0]   services:
2024-04-05 00:02:54,391 DEBUG   [dr1/0]     mon: 1 daemons, quorum a (age 74s)
2024-04-05 00:02:54,391 DEBUG   [dr1/0]     mgr: a(active, since 36s)
2024-04-05 00:02:54,391 DEBUG   [dr1/0]     osd: 1 osds: 0 up, 1 in (since 24s)
2024-04-05 00:02:54,392 DEBUG   [dr1/0] 
2024-04-05 00:02:54,392 DEBUG   [dr1/0]   data:
2024-04-05 00:02:54,392 DEBUG   [dr1/0]     pools:   0 pools, 0 pgs
2024-04-05 00:02:54,392 DEBUG   [dr1/0]     objects: 0 objects, 0 B
2024-04-05 00:02:54,392 DEBUG   [dr1/0]     usage:   0 B used, 0 B / 0 B avail
2024-04-05 00:02:54,392 DEBUG   [dr1/0]     pgs:
2024-04-05 00:02:54,471 INFO    [dr1/0] addons/rook-toolbox/start completed in 11.43 seconds
2024-04-05 00:02:54,472 INFO    [dr1/0] Running addons/rook-pool/start
2024-04-05 00:02:54,756 DEBUG   [dr1/0] Creating rbd pool and storage class
2024-04-05 00:02:55,209 DEBUG   [dr1/0] cephblockpool.ceph.rook.io/replicapool created
2024-04-05 00:02:55,260 DEBUG   [dr1/0] storageclass.storage.k8s.io/rook-ceph-block created
2024-04-05 00:02:55,262 DEBUG   [dr1/0] Waiting until ceph block pool is ready
2024-04-05 00:02:55,503 DEBUG   [dr1/0] 'cephblockpool/replicapool' output='jsonpath={.status.phase}' found in 0.24 seconds
2024-04-05 00:04:34,734 DEBUG   [dr1/0] cephblockpool.ceph.rook.io/replicapool condition met
2024-04-05 00:04:34,737 DEBUG   [dr1/0] Waiting for replica pool peer token
2024-04-05 00:04:34,999 DEBUG   [dr1/0] cephblockpool.ceph.rook.io/replicapool condition met
2024-04-05 00:04:35,177 DEBUG   [dr1/0] ceph pool status:
2024-04-05 00:04:35,177 DEBUG   [dr1/0]   info:
2024-04-05 00:04:35,177 DEBUG   [dr1/0]     rbdMirrorBootstrapPeerSecretName: pool-peer-token-replicapool
2024-04-05 00:04:35,177 DEBUG   [dr1/0]   observedGeneration: 1
2024-04-05 00:04:35,178 DEBUG   [dr1/0]   phase: Ready
2024-04-05 00:04:35,178 DEBUG   [dr1/0] 
2024-04-05 00:04:35,219 INFO    [dr1/0] addons/rook-pool/start completed in 100.75 seconds
2024-04-05 00:07:35,741 INFO    [rdr/0] Running addons/rbd-mirror/start
2024-04-05 00:07:35,984 DEBUG   [rdr/0] Getting mirroring info site name for cluster 'dr1'
2024-04-05 00:07:36,145 DEBUG   [rdr/0] 'cephblockpools.ceph.rook.io/replicapool' output='jsonpath={.status.mirroringInfo.site_name}' found in 0.17 seconds
2024-04-05 00:07:36,145 DEBUG   [rdr/0] Getting rbd mirror boostrap peer secret name for cluster 'dr1'
2024-04-05 00:07:36,313 DEBUG   [rdr/0] Getting secret pool-peer-token-replicapool token for cluster 'dr1'
2024-04-05 00:07:36,454 DEBUG   [rdr/0] Getting mirroring info site name for cluster 'dr2'
2024-04-05 00:07:36,598 DEBUG   [rdr/0] 'cephblockpools.ceph.rook.io/replicapool' output='jsonpath={.status.mirroringInfo.site_name}' found in 0.14 seconds
2024-04-05 00:07:36,598 DEBUG   [rdr/0] Getting rbd mirror boostrap peer secret name for cluster 'dr2'
2024-04-05 00:07:36,782 DEBUG   [rdr/0] Getting secret pool-peer-token-replicapool token for cluster 'dr2'
2024-04-05 00:07:36,910 DEBUG   [rdr/0] Setting up mirroring from 'dr2' to 'dr1'
2024-04-05 00:07:36,911 DEBUG   [rdr/0] Applying rbd mirror secret in cluster 'dr1'
2024-04-05 00:07:37,172 DEBUG   [rdr/0] secret/7995131f-5ee5-49cd-8c7c-ddfe0ccf086a created
2024-04-05 00:07:37,177 DEBUG   [rdr/0] Configure peers for cluster 'dr1'
2024-04-05 00:07:37,400 DEBUG   [rdr/0] cephblockpool.ceph.rook.io/replicapool patched
2024-04-05 00:07:37,405 DEBUG   [rdr/0] Apply rbd mirror to cluster 'dr1'
2024-04-05 00:07:37,690 DEBUG   [rdr/0] cephrbdmirror.ceph.rook.io/my-rbd-mirror created
2024-04-05 00:07:37,698 DEBUG   [rdr/0] Setting up mirroring from 'dr1' to 'dr2'
2024-04-05 00:07:37,698 DEBUG   [rdr/0] Applying rbd mirror secret in cluster 'dr2'
2024-04-05 00:07:38,014 DEBUG   [rdr/0] secret/34169d10-23bb-4087-b218-6b474627b8e7 created
2024-04-05 00:07:38,022 DEBUG   [rdr/0] Configure peers for cluster 'dr2'
2024-04-05 00:07:38,201 DEBUG   [rdr/0] cephblockpool.ceph.rook.io/replicapool patched
2024-04-05 00:07:38,208 DEBUG   [rdr/0] Apply rbd mirror to cluster 'dr2'
2024-04-05 00:07:38,485 DEBUG   [rdr/0] cephrbdmirror.ceph.rook.io/my-rbd-mirror created
2024-04-05 00:07:38,490 DEBUG   [rdr/0] Waiting until rbd mirror is ready in cluster 'dr1'
2024-04-05 00:07:48,266 DEBUG   [rdr/0] 'cephrbdmirror/my-rbd-mirror' output='jsonpath={.status.phase}' found in 9.78 seconds
2024-04-05 00:07:48,611 DEBUG   [rdr/0] cephrbdmirror.ceph.rook.io/my-rbd-mirror condition met
2024-04-05 00:07:48,812 DEBUG   [rdr/0] rbd mirror status:
2024-04-05 00:07:48,812 DEBUG   [rdr/0]   observedGeneration: 1
2024-04-05 00:07:48,812 DEBUG   [rdr/0]   phase: Ready
2024-04-05 00:07:48,812 DEBUG   [rdr/0] 
2024-04-05 00:07:48,812 DEBUG   [rdr/0] Waiting until rbd mirror is ready in cluster 'dr2'
2024-04-05 00:07:54,960 DEBUG   [rdr/0] 'cephrbdmirror/my-rbd-mirror' output='jsonpath={.status.phase}' found in 6.15 seconds
2024-04-05 00:07:55,222 DEBUG   [rdr/0] cephrbdmirror.ceph.rook.io/my-rbd-mirror condition met
2024-04-05 00:07:55,457 DEBUG   [rdr/0] rbd mirror status:
2024-04-05 00:07:55,457 DEBUG   [rdr/0]   observedGeneration: 1
2024-04-05 00:07:55,457 DEBUG   [rdr/0]   phase: Ready
2024-04-05 00:07:55,457 DEBUG   [rdr/0] 
2024-04-05 00:07:55,457 DEBUG   [rdr/0] Waiting until ceph mirror daemon is healthy in cluster 'dr1'
```

The wait times out after 600 seconds:

```
2024-04-05 00:17:55,596 ERROR   Command failed
Traceback (most recent call last):
  ...
drenv.commands.Error: Command failed:
   command: ('addons/rbd-mirror/start', 'dr1', 'dr2')
   exitcode: 1
   error:
      Traceback (most recent call last):
        ...
      drenv.commands.Error: Command failed:
         command: ('kubectl', 'wait', '--context', 'dr1', 'cephblockpools.ceph.rook.io', 'replicapool', '--for=jsonpath={.status.mirroringStatus.summary.daemon_health}=OK', '--namespace=rook-ceph', '--timeout=600s')
         exitcode: 1
         error:
            error: timed out waiting for the condition on cephblockpools/replicapool
```

## Tasks

- [x] Reproduce and stop the stress test (run with -x)
- [x] Collect logs and state at the time of the failure
- [ ] Report rook/ceph bug

**Comment by nirs** [comment]
Duplicate of #1332. The new issue has more details so I'm closing this one.
