### ISSUE TITLE
drenv: Use local registry

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#1334]
Starting regional DR environment downloads log of images per cluster. This is very slow in the CI lab or when using slow connection locally (e.g. cellular connection).

## Images in regional DR env managed cluster

```
$ minikube image ls --format table -p dr1
```

|                               Image                               |             Tag              |   Image ID    |  Size  |
|-------------------------------------------------------------------|------------------------------|---------------|--------|
| quay.io/submariner/submariner-globalnet                           | 0.17.0                       | sha256:dd5363 | 23.5MB |
| quay.io/submariner/submariner-route-agent                         | 0.17.0                       | sha256:c2610b | 66.5MB |
| registry.k8s.io/pause                                             | 3.9                          | sha256:e6f181 | 322kB  |
| registry.k8s.io/sig-storage/csi-node-driver-registrar             | v2.10.0                      | sha256:b57209 | 10.9MB |
| quay.io/stolostron/multicloud-manager                             | latest                       | sha256:49c0f9 | 205MB  |
| quay.io/csiaddons/k8s-controller                                  | v0.8.0                       | sha256:febdac | 26MB   |
| quay.io/submariner/submariner-gateway                             | 0.17.0                       | sha256:449594 | 67.8MB |
| registry.k8s.io/kube-scheduler                                    | v1.28.3                      | sha256:6d1b4f | 18.8MB |
| gcr.io/kubebuilder/kube-rbac-proxy                                | v0.8.0                       | sha256:ad393d | 20MB   |
| quay.io/open-cluster-management/governance-policy-framework-addon | v0.13.0                      | sha256:76b4ea | 67.1MB |
| quay.io/open-cluster-management/multicloud-operators-subscription | v0.13.0                      | sha256:d09a25 | 267MB  |
| quay.io/submariner/lighthouse-coredns                             | 0.17.0                       | sha256:c35911 | 15.5MB |
| gcr.io/k8s-minikube/storage-provisioner                           | v5                           | sha256:6e38f4 | 9.06MB |
| quay.io/open-cluster-management/config-policy-controller          | v0.13.0                      | sha256:b5be08 | 71MB   |
| quay.io/operatorhubio/catalog                                     | latest                       | sha256:13b5ee | 150MB  |
| quay.io/submariner/nettest                                        | 0.17.0                       | sha256:bb10b0 | 10.2MB |
| quay.io/backube/volsync                                           | 0.9.0                        | sha256:3ac991 | 276MB  |
| registry.k8s.io/sig-storage/csi-provisioner                       | v4.0.0                       | sha256:6cc68f | 29.3MB |
| quay.io/nirsof/busybox                                            | stable                       | sha256:3f57d9 | 2.28MB |
| quay.io/submariner/submariner-operator                            | 0.17.0                       | sha256:54021b | 11.9MB |
| registry.k8s.io/sig-storage/csi-snapshotter                       | v7.0.1                       | sha256:dd1718 | 27.6MB |
| docker.io/kindest/kindnetd                                        | v20230809-80a64d96           | sha256:c7d129 | 27.7MB |
| quay.io/open-cluster-management/work                              | v0.13.1                      | sha256:db3b4f | 80MB   |
| quay.io/nirsof/nginx                                              | stable-alpine-slim           | sha256:f852d2 | 7.47MB |
| quay.io/nirsof/velero-plugin-for-aws                              | v1.2.1                       | sha256:40c62d | 45.4MB |
| quay.io/submariner/nettest                                        | 0.15.2                       | sha256:30700a | 10.1MB |
| registry.k8s.io/sig-storage/csi-attacher                          | v4.5.0                       | sha256:aefda5 | 27.4MB |
| quay.io/brancz/kube-rbac-proxy                                    | v0.14.0                      | sha256:cf357a | 24.6MB |
| registry.k8s.io/kube-proxy                                        | v1.28.3                      | sha256:bfc896 | 24.6MB |
| quay.io/open-cluster-management/registration-operator             | v0.13.1                      | sha256:4fbba0 | 80.2MB |
| registry.k8s.io/coredns/coredns                                   | v1.10.1                      | sha256:ead0a4 | 16.2MB |
| quay.io/minio/minio                                               | RELEASE.2024-03-15T01-07-19Z | sha256:3ef82e | 53.5MB |
| quay.io/cephcsi/cephcsi                                           | v3.10.2                      | sha256:10105e | 560MB  |
| registry.k8s.io/etcd                                              | 3.5.9-0                      | sha256:73deb9 | 103MB  |
| quay.io/csiaddons/k8s-sidecar                                     | v0.8.0                       | sha256:8c39e3 | 47.4MB |
| quay.io/nirsof/velero                                             | v1.12.1                      | sha256:3ba873 | 60.2MB |
| registry.k8s.io/kube-apiserver                                    | v1.28.3                      | sha256:537434 | 34.7MB |
| registry.k8s.io/sig-storage/csi-resizer                           | v1.10.0                      | sha256:0bc2cd | 28MB   |
| quay.io/ceph/ceph                                                 | v18                          | sha256:1c40e0 | 447MB  |
| quay.io/ceph/ceph                                                 | v18.2.2                      | sha256:1c40e0 | 447MB  |
| quay.io/open-cluster-management/registration                      | v0.13.1                      | sha256:5cb7fd | 79.7MB |
| quay.io/submariner/lighthouse-agent                               | 0.17.0                       | sha256:02d127 | 10MB   |
| registry.k8s.io/kube-controller-manager                           | v1.28.3                      | sha256:10baa1 | 33.4MB |
| docker.io/rook/ceph                                               | v1.13.8                      | sha256:4276e6 | 467MB  |

## Images in a regional DR env hub

```
$ minikube image ls --format table -p hub
```

|                               Image                                |        Tag         |   Image ID    |  Size  |
|--------------------------------------------------------------------|--------------------|---------------|--------|
| quay.io/open-cluster-management/multicloud-operators-channel       | v0.13.0            | sha256:fcad42 | 72.4MB |
| quay.io/open-cluster-management/multicloud-operators-subscription  | v0.13.0            | sha256:d09a25 | 267MB  |
| registry.k8s.io/kube-controller-manager                            | v1.28.3            | sha256:10baa1 | 33.4MB |
| registry.k8s.io/etcd                                               | 3.5.9-0            | sha256:73deb9 | 103MB  |
| docker.io/kindest/kindnetd                                         | v20230809-80a64d96 | sha256:c7d129 | 27.7MB |
| quay.io/open-cluster-management/governance-policy-propagator       | v0.13.0            | sha256:a04954 | 63.8MB |
| quay.io/open-cluster-management/work                               | v0.13.1            | sha256:db3b4f | 80MB   |
| quay.io/stolostron/multicloud-manager                              | latest             | sha256:49c0f9 | 205MB  |
| quay.io/operatorhubio/catalog                                      | latest             | sha256:13b5ee | 150MB  |
| quay.io/submariner/submariner-operator                             | 0.17.0             | sha256:54021b | 11.9MB |
| registry.k8s.io/kube-apiserver                                     | v1.28.3            | sha256:537434 | 34.7MB |
| registry.k8s.io/kube-scheduler                                     | v1.28.3            | sha256:6d1b4f | 18.8MB |
| gcr.io/k8s-minikube/storage-provisioner                            | v5                 | sha256:6e38f4 | 9.06MB |
| quay.io/open-cluster-management/governance-policy-addon-controller | v0.13.0            | sha256:d8a3ab | 79.9MB |
| quay.io/open-cluster-management/placement                          | v0.13.1            | sha256:d1dd60 | 77.1MB |
| registry.k8s.io/kube-proxy                                         | v1.28.3            | sha256:bfc896 | 24.6MB |
| registry.k8s.io/pause                                              | 3.9                | sha256:e6f181 | 322kB  |
| quay.io/open-cluster-management/addon-manager                      | v0.13.1            | sha256:236c1f | 78.7MB |
| quay.io/open-cluster-management/registration-operator              | v0.13.1            | sha256:4fbba0 | 80.2MB |
| quay.io/open-cluster-management/registration                       | v0.13.1            | sha256:5cb7fd | 79.7MB |
| registry.k8s.io/coredns/coredns                                    | v1.10.1            | sha256:ead0a4 | 16.2MB |

## Total images size

```
$ minikube image ls --format json -p dr1 | jq -r '.[].size' | awk '{sum+=$1} END {print sum/(1024*1024*1024), "GiB"}'
3.66595 GiB

$ minikube image ls --format json -p dr2 | jq -r '.[].size' | awk '{sum+=$1} END {print sum/(1024*1024*1024), "GiB"}'
3.66595 GiB

$ minikube image ls --format json -p hub | jq -r '.[] | .size' | awk '{sum+=$1} END {print sum/(1024*1024*1024), "GiB"}'
1.51436 GiB
```

## Tasks

- [x] Document how to setup a local registry ([see test registry README](https://github.com/RamenDR/ramen/tree/main/test/registry))
- [ ] Find all images (from the manifests? from build using remote images?)
- [ ] Pull the images during `drenv fetch` to local registry
- [ ] Modify the addons manifests to use the local images
- [ ] Configure minikube to allow local insecure registry
- [ ] Clear cached images in `drenv clear`
