### ISSUE TITLE
e2e task/comments tracker

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#1398]
- [ ] [This](https://github.com/RamenDR/ramen/blob/9b7fc7831502fd7fdb8f295b058c7eef25722b15/e2e/testcontext/testcontext.go#L37) should be a for loop, i.e we look for a context till we hit the root context. Reason being there maybe a sub tree of tests where context is set at a level higher than the parent, and we should be able to find the same.
- [ ] Decide on name/namespace for various test, such that they do not interfere with each other, and at the same time we need to test cases where there are multiple workloads within the same namespace
- [x] Create channel as a per-requisite to all tests, than with each deployer
- [ ] Check to see if gomega as a matcher would be better for retries
- [x] Move to an config YAML file than env variables for e2e defaults
- [ ] Change command line options to a single config option, and read all options from the passed in YAML
- [ ] IsWorkloadSupported function in the interface has minimal intelligence and skips by name but should eventually do it by analyzing the workload.

**Comment by nirs** [comment]
All items here are already handled or outdated.
