### ISSUE TITLE
Tracker: PeerClass processing across various reconcilers

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#1616]
- [ ] Update design with clusterID list information for a peer
- [ ] Add envtest for `getClusterClasses` and related DRPolicy event based reconciles
- [ ] Add support to claim and process claims for VolumeGroupSnapshotClass
- [ ] Add support to claim and process claims for VolumeGroupReplicationClass
