### ISSUE TITLE
e2e: Support any cluster type

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#1716]
There are some cluster details that are now hard coded (e.g. clusterset name). We ned to make all values part of the config so one can create a config that works with any cluster (e.g. OpenShift test cluster).

Depends on #1771 

## Tasks

- [ ] Create configuration for our openshift test clusters so developers do not need to start from scratch
- [ ] Create configuration for QE test clusters if possible, so tester do not have to start from scratch
- [ ] Test on all cluster types

**Comment by parikshithb** [comment]
Closing this issue, since users will not use ramen e2e to run on openshift clusters but rather use ramenctl directly. So it is not required to provide separate configuration sample like for QE openshift clusters.
