### ISSUE TITLE
Improve drenv error messages

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#648]
The typical error is a timeout from kubectl command trying to access remote server:

```
2022-12-01 11:40:01,914 ERROR   [env3-dr2/2] Cluster failed
Traceback (most recent call last):
  File "/home/nsoffer/ramen/test/drenv/__main__.py", line 102, in execute
    f.result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/nsoffer/ramen/test/drenv/__main__.py", line 204, in run_worker
    run_script(script, worker["name"])
  File "/home/nsoffer/ramen/test/drenv/__main__.py", line 210, in run_script
    run(script["file"], *script["args"], name=name)
  File "/home/nsoffer/ramen/test/drenv/__main__.py", line 237, in run
    raise RuntimeError(
RuntimeError: [env3-dr2/2] Command ('olm/start', 'env3-dr2') failed rc=1

Last messages:
    customresourcedefinition.apiextensions.k8s.io/catalogsources.operators.coreos.com condition met
    customresourcedefinition.apiextensions.k8s.io/clusterserviceversions.operators.coreos.com condition met
    customresourcedefinition.apiextensions.k8s.io/installplans.operators.coreos.com condition met
    customresourcedefinition.apiextensions.k8s.io/olmconfigs.operators.coreos.com condition met
    customresourcedefinition.apiextensions.k8s.io/operatorconditions.operators.coreos.com condition met
    customresourcedefinition.apiextensions.k8s.io/operatorgroups.operators.coreos.com condition met
    customresourcedefinition.apiextensions.k8s.io/operators.operators.coreos.com condition met
    customresourcedefinition.apiextensions.k8s.io/subscriptions.operators.coreos.com condition met
  * Deploying olm
  Unable to connect to the server: dial tcp: lookup objects.githubusercontent.com on 127.0.0.1:53: read udp 127.0.0.1:37310->127.0.0
.1:53: i/o timeout
  Traceback (most recent call last):
    File "/home/nsoffer/ramen/test/olm/start", line 40, in <module>
      drenv.kubectl(
    File "/home/nsoffer/ramen/test/drenv/__init__.py", line 50, in kubectl
      return run(*cmd, input=input, verbose=verbose)
    File "/home/nsoffer/ramen/test/drenv/__init__.py", line 163, in run
      cp = subprocess.run(
    File "/usr/lib64/python3.9/subprocess.py", line 528, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '('minikube', 'kubectl', '--profile', 'env3-dr2', '--', 'apply', '--filename', 'https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.22.0/olm.yaml')' returned non-zero exit status 1.
```

The actual error is logged somewhere in the middle:

```
  Unable to connect to the server: dial tcp: lookup objects.githubusercontent.com on 127.0.0.1:53: read udp 127.0.0.1:37310->127.0.0.1:53: i/o timeout
```

It should be logged in the traceback message in a way that is easy to inspect:

```
  subprocess.CalledProcessError:
    command:
       - 'minikube'
       - 'kubectl'
       - '--profile'
       - 'env3-dr2'
       - '--'
       - 'apply'
       - '--filename'
       - 'https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.22.0/olm.yaml'
    returncode: 1
    stdout: '...'
    stderr: 'Unable to connect to the server: dial tcp: lookup objects.githubusercontent.com on 127.0.0.1:53: read udp 127.0.0.1:37310->127.0.0.1:53: i/o timeout'
```

The issue is redirecting stderr to stdout. This can work with bad programs that mix stdout and stderr or use only stdout, but makes it harder to debug.

It will also be useful if we can easily process errors with a program. For example in CI environment we would like to keep stats on errors so we can focus on the most common errors.

Expected result:
- Include command arguments, returncode, stdout, and stderr in the exception
- Format errors so they are easy to inspect
- Format errors so they can be used by machines?

Tasks:
- [x] Helper to stream stdout and stderr separately from child process (#658)
- [x] Capture child process stderr separately from stdout (#663)
- [x] Improve error messages in drenv tool (#663)
- [x] Add optional output for commands.Error
- [x] Add commands.run
- [x] Use standalone kubctl executable
- [x] Add drenv.kubectl_get (run)
- [x] Add drenv.kubectl_exec (run)
- [x] Add drenv.kubectl_apply (watch)
- [x] Add drenv.kubectl_rollout (watch)
- [x] Add drenv.kubectl_wait (watch)
- [x] Add drenv.kubectl_delete (watch)
- [x] Add drenv.kubectl_patch (watch)
- [x] Add drenv.kubectl_config (run)
- [x] Move drenv.kubectl_* to drenv.kubectl.*                                                                                    
- [x] Fix error handling in drenv.run
- [x] Extract clusteradm module
