### ISSUE TITLE
Velero integration in test environment

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#662]
According to @ShyamsundarR velero is not installed automatically by ramnen, so we need to
install it on the test environment as part of the deployment.

We have everything needed for deployment and testing the deployment here:
https://velero.io/docs/v1.11/contributions/minio/

There are also exiting configuration and setup code in:
- hack/recipe_e2e
- hack/velero-test.sh
- hack/shio-demo.sh

## Tasks

- [x] Install velero crds so we don't need to disabale kube object protection in ramen config map.
- [x] Add velero configuration in `ramenctl config`
- [x] Install velero `velero/start`
- [x] Generate the velero CRDs instead of using the copy in hack?
- [x] Add velero to `regional-dr.yaml`

If we need a faster solution, velero can be disabled in ramen config.
