### ISSUE TITLE
[drenv] Basic ramen docs

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#760]
The following notes are provided to enable further automation in the env scripts to make it easier to test with a ramen bundle install. Some steps are also common and needed for `make deploy` based ramen installs.

Intention of this issue would be to convert each of the steps that need to be automated to an issue, and track it here, changing the instructions as they are fixed to reflect a series of steps to take to test using drenv.

- [ ] Created a drenv using the regional-dr.yaml environment (#607)
- [x] Install ramen on the hub using the upstream [bundles](https://github.com/RamenDR/ramen/blob/main/docs/install.md#install-ramen-hub-operator)
- [ ] Configure ramen (#777)
- [ ] Deploy a DR protected workload (#779)
- [ ] Failover DR protected worlload (#780)
- [ ] Relocate DR protected workload (#781)
- [ ] Undeploy DR protected workload (#782)

**Comment by nirs** [comment]
@ShyamsundarR should we create the secrets as part of the minio deployment, or
this is ramen specifc configuration?

If we have ramen specific configuration, shouldn't it be part of `make deploy-*`?

If this is kind of one time configuration that need to be done once after creating
the environemnt, we likey need to add a new `ramen` component preparing the environemnt
for deploying ramen.

My assumption is that deploying ramen is something you would do multiple times with
the same enviroment, for example:

- build test env
- repeat:
  - hack ramen code ...
  - deploy ramen
  - test ...

**Comment by ShyamsundarR** [comment]
> @ShyamsundarR should we create the secrets as part of the minio deployment, or this is ramen specifc configuration?

It is ramen specific configuration

> 
> If we have ramen specific configuration, shouldn't it be part of `make deploy-*`?

It is configuration, not part of deployment. IOW, this is post install configuration that needs to be done and is specific to each cluster where ramen is installed in. For example, here we ask for the s3 store details that Ramen should be interacting with, which is not part of the deployment.

> 
> If this is kind of one time configuration that need to be done once after creating the environemnt, we likey need to add a new `ramen` component preparing the environemnt for deploying ramen.

For a given drenv, this is a one-time configuration post install of ramen.

> 
> My assumption is that deploying ramen is something you would do multiple times with the same enviroment, for example:
> 
>     * build test env
> 
>     * repeat:
>       
>       * hack ramen code ...
>       * deploy ramen

If we are only changing the ramen operator image (which is >95% of the time) to test and validate it again, we do not need to rebuild the env or re-configure the env. We would just replace the operator image and re-run the test case.

If testing ramen install or items related to auto-deploy of ramen bundles and secrets to dr clusters, we would recreate drenv fully (or uninstall/reinstall just ramen bundles and componsnts).

In both cases configuration automation from drenv for ramen is helpful and needed as it avoids a lot of manual steps, that are env specific.

>       * test ...

**Comment by nirs** [comment]
Based [@ShyamsundarR commemnt](https://github.com/RamenDR/ramen/issues/760#issuecomment-1465197797), we need to have 4 steps:

- build ramen image/bundle that work with developer/CI test env
- push image/bundle to developer/CI repo or directly to cluster
- deploy ramen in test env
- configure ramen for using s3 in the test env

Developer should be able to run all of them automatically for testing changes
during edit-test cycle:

    make drenv

Developer should be able to run separate steps if needed:

    make drenv-image-build
    make drenv-image-push
    make drenv-ramen-deploy
    make drenv-ramen-configure

The makefile will use environment variables with the names of the clusters:

    HUB_CLUSTER=hub
    MANAGED_CLUSTERS="dr1 dr2"

A developer can modify the makefile defaults to test a different environment, but out
of the box, running make drenv will do the right thing.

Example developer workflow:

    cd test
    source ~/.venv/ramen/bin/activate
    drenv start regional-dr.yaml

In antoher shell, or via editor console:

    while true; do
        edit ...
        make drenv
        test ...

@ShyamsundarR what do you think?

**Comment by ShyamsundarR** [comment]
@nirs I think we should not use make targets for this purpose, as the work to be done is more expansive. This should be part of drenv (unless you were referring to the drenv Makefile for the targets) as that has the required environment details and can construct the required resources for the same.

The intention is to install and configure ramen in a given dr environment, and towards this I see the following commands (command structure maybe different, but intent is described here):
1. drenv deploy sources
   - Ensure bundle based deploy is not active
   - Run from source directory/branch that needs to be deployed
   - make docker-build
   - load built image to cluster
   - make deploy-hub
      - Set ramen config to not auto deploy cluster, as we are not using bundles
   - make deploy-dr-cluster
1. drenv deploy bundle
   - Ensure source based deployment is not active
   - Deploy catalog source to all clusters
   - Deploy ramen hub bundle
   - Ability to use a user defined catalog source should be available, instead of the upstream catalog, which would be the default
   - (optional) build and push image/bundle/catalog before rolling out the same
   - Note: bundle deploy will not be done again, it would be done once and techincally the bundle version would be incremented to update the cluster. In our case we could uninstall the bundle and then reinstall it again
1. drenv configure ramen
   - Optional command, can be folded with one of the above commands
   - Create s3 secret in ramen namespace on all clusters
   - Update ramen config map with s3 access points on all clusters
   - Create DRCluster resource for each managed cluster
      - Create them as the same region or different regions based on the env (sync/async)
   - Create a DRPolicy resource at the hub
      - Default to 1 minute schedule interval (override with --schedule-interval option at the CLI) if env is async
      - Default to sync in case env is sync
   - (optional) Create the Channel resource for ocm-ramen-samples for any further testing
1. drenv undeploy
   - Undeploy ramen, however it was deployed. Useful when testing bundle based installs to refresh with a new built bundle in the next run

With the possible flow as above, a dev would do the following:
1. Create a drenv for testing
2. Edit...
3. drenv deploy sources
4. test
5. Repeat (2/3/4) as needed

A dev interested in testing using bundles would replace 3 with `drenv deploy bundle`. Assuming a catalog and bundle override is in use to push these images to and deploy them from a user specified catalog source.

A e2e CI run would potentially use `drenv deploy bundle` with per build bundle catalog and images, and then run the automated e2e tests for the flavor of the environment (regional/metro/recipe/etc.)

A post merge CI run (or release run) would invoke the same as the e2e, except with the published ramen catalog and bundles.

**Comment by ShyamsundarR** [comment]
Added some potential test case flow in e2e [here](https://github.com/RamenDR/ramen/issues/134#issuecomment-1466991850). The CI run may start configuring and then running the tests, than starting at a point where it is configured BUT, this may come later than other tests that expect a configured setup, and may need consideration appropriately.
