### ISSUE TITLE
Submariner integration in drenv test environment

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#916]
To test volsync we need to deploy submariner in the environment.

## Deployment

Submariner is using a broker which can be one of the clusters in the system:
https://submariner.io/images/submariner/architecture.jpg

Submariner uses one cluster as a broker - there is no broker service, it uses k8s
API to store submariner configuration. All submariner cluster access the broker 
cluster to get the configuration.

We can install the broker on one of the managed clusters, or on the hub. Both ways
should work.

There is also submariner ACM addon - not sure what it does and if we need it.
https://github.com/stolostron/submariner-addon

Need to check how this is done in ODF and likely use the same solution:
https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html/manage_cluster/submariner#deploying-submariner

Submariner supports several cable drivers: ('libreswan', 'wireguard', 'vxlan'). `libreswan`
does not work since minikube is missing some IPSEC bits. `wireguard` seems to be missing
as well and minikube is not easy to modify. `vxlan` works and is also the best option for
a testing environment.

Submariner deployment can be verified with `subctl verify` command, but this runs the entire
submariner end to end test suite and its way too slow (~10 minutes) to run as a self test.
We need to find a fast basic test to use as a self test.

## Tasks

- [x] Pick deployment suitable for minikube clusters
- [x] Add submariner to test regional-dr environment
- [x] Add self test for verifying the deployment
