### ISSUE TITLE
Test basic-test with openshift clusters

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#960]
We want to be able to run ramen basic-test with openshift clusters for testing upstream
ramen changes with openshift.

Depends on #959.

## Tasks

1. [ ] Get openshift cluster kubeconfigs for hub, cluster1, cluster2
   - `oc login` for every cluster should import the config into .kube/cnfig

1. [ ] Deploy and configure latest ramen from git
   - how?
   - do we need [docs/deploy/openshift.md](docs/deploy/openshift.md)?

1. [ ] Create environment file for the external clusters

   ```yaml
   # ocp.yaml
   ---
   ramen:
     hub: hub
     clusters: [cluster1, cluster2]
     topology: regional-dr
   profiles:
     - name: hub
       external: true
     - name: cluster1
       external: true
     - name: cluster2
       external: true
   ```

1. [ ] Run basic test

   ```
   test/basic-test/run ocp.yaml
   ```

1. [ ] Automate steps 2, 3 so we don't have to do this manually. It will be useful to
   have a tool for importing configs and creating environment file for the configs:

   ```sh
   drenv generate --hub hub.kubeconfig --cluster cluster1.kubeconfig --cluster cluster2.kubeconfig
   ```

Open other issue if needed if the test does not work with openshift clusters.

**Comment by parikshithb** [comment]
Closing as obsolete. The basic-test infrastructure has been removed in favor of the e2e testing framework.
cc @nirs
